version: '3'
services:
  db:
    image: mongo:3.4
    restart: always
  backend:
    image: node:8.1
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
    restart: always
  frontend:
    image: nginx:1.13
    volumes:
     - ./frontend:/usr/share/nginx/html/
    ports:
      - 8087:80
    restart: always
